title: BootCamp for B4
description:
    Training for new B4, Imai Laboratory, Keio University.
baseurl: ""
url: "https://www.ailab.ics.keio.ac.jp/b4_induction_training"

email: uchiumi@ailab.ics.keio.ac.jp
twitter_username: imailab
github_username: imai-laboratory

footer_content:
    Copyright &copy; Imai laboratory 2020 Powered by <a target="_blank" href="https://jekyllrb.com/">Jekyll</a>,&nbsp; Proudly hosted by <a target="_blank" href="https://pages.github.com/">GitHub Pages</a>.

markdown: kramdown

# Build settings
# paginate_path: "page:num"
# paginate: 3

sass:
  style: expanded

plugins:
  - jekyll-paginate
  - jekyll-feed
#   - jekyll-jupyter-notebook
